[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.9.0"
pest = "2"
pest_derive = "2"
lazy_static = "1.4.0"
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"
