use std::str::FromStr;
use ast::{Expr, Opcode};

grammar;

pub Expr: f32 = {
    <l:Expr> "+" <r:Factor> => l + r,
    <l:Expr> "-" <r:Factor> => l - r,
    Factor,
};

Factor: f32 = {
    <l:Factor> "*" <r:Term> => l * r,
    <l:Factor> "/" <r:Term> => l / r,
    Term,
};

Term: f32 = {
    Num,
    "(" <Expr> ")",
};

Num: f32 = {
    r"[0-9]+\.?[0-9]*" => f32::from_str(<>).unwrap(),
};

# vim: ft=lalrpop:
